"""Add thumbnail_filename to ListingImage

Revision ID: 48e4d4abe479
Revises: 04ede7750476
Create Date: 2025-07-15 18:30:35.742836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e4d4abe479'
down_revision = '04ede7750476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_filename')

    # ### end Alembic commands ###
