# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2025 Fernando "ferabreu" Mees Abreu
#
# Licensed under the GNU General Public License v2.0 (GPL-2.0-only).
# See LICENSE file in the project root for full license information.
#
"""
This migration was written and annotated by GitHub Copilot at the request of Fernando "ferabreu" Mees Abreu (https://github.com/ferabreu).

Add thumbnail_filename to ListingImage

Revision ID: 48e4d4abe479
Revises: 04ede7750476
Create Date: 2025-07-15 18:30:35.742836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e4d4abe479'
down_revision = '04ede7750476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_image', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_filename')

    # ### end Alembic commands ###
